services:
  tesp-api:
    build:
      context: ./
      dockerfile: docker/tesp_api/Dockerfile
      target: development
    image: tesp-api
    profiles: ["api", "all"]
    environment:
      - CONTAINER_TYPE=docker  # Set to "docker", "singularity", or "both"
    container_name: tesp-api
    privileged: true
    ports:
      - "8080:8080"
    depends_on:
      - tesp-db
    volumes:
      - ./:/app
      - /opt/pysetup/files/staging/:/opt/pysetup/files/staging/
      #    extra_hosts:
      #      - "host.docker.internal:host-gateway"

  tesp-db:
    image: mongo:latest
    profiles: ["api", "all"]
    container_name: tesp-db
    volumes:
      - ./docker/mongodb/data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=tesp
    ports:
      - "8081:27017"
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1

  pulsar_rest:
    build:
      context: ./docker/pulsar_rest
      dockerfile: Dockerfile
      target: development
    image: pulsar_rest
    profiles: ["pulsar", "all"]
    container_name: pulsar-rest
    privileged: true
    expose:
      - "8913"
    volumes:
      - ./docker/pulsar_rest/app.yml:/opt/pysetup/app.yml
# DIND - problem with resource limitation, missing cgroups inside
#      - ./docker/pulsar_rest/data/:/opt/pysetup/files/staging/
# DOOD
      - /opt/pysetup/files/staging/:/opt/pysetup/files/staging/
      - /var/run/docker.sock:/var/run/docker.sock

# Some cloud providers may require a lower MTU!
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1442
