name: ci

on: [push, pull_request]

jobs:

  static-code-analysis:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: check out repository
        uses: actions/checkout@v4

      # Docker Compose up command
      - name: Run Docker Compose
        run: |
          docker compose up -d --build
